switched entirly to downloading the needed files and not using git submodules, to make the repo smaller

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,19 @@
 #!/bin/bash
 
 TARGET=${1:-x86_64}
+BOOTLOADER=${2:-limine}
+shift
 shift
 
-./env/configure $TARGET
-./env/build $TARGET
-qemu-system-$TARGET -name "Leaf $TARGET" -drive file="release/Leaf-$TARGET-$(date +%B-%Y).iso",index=0,format=raw "$@"
+ISO_FILE="release/Leaf-$TARGET-$(date +%B-%Y).iso"
+
+./env/configure "$TARGET" "$BOOTLOADER"
+./env/build "$TARGET" "$BOOTLOADER"
+
+if [ ! -f "$ISO_FILE" ]; then
+    echo -e ">>> \033[1m\033[31mFailed to build? Didn't find '$ISO_FILE'!\033[0m"
+    exit 1
+fi
+
+echo -e ">>> \033[32mSuccessfully built '$ISO_FILE'.\033[0m"
+qemu-system-"$TARGET" -name "Leaf $TARGET" -drive file="$ISO_FILE",index=0,format=raw "$@"
